name: Ubuntu 22.04

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ubuntu:
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      dockerfile: ./Dockerfile
      image: ubuntu:22.04
      base_image: umtdg/ubuntu:22.04
